// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models.Entities;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(ODTutorContext))]
    [Migration("20240802155509_Add_Type_For_Report")]
    partial class Add_Type_For_Report
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("GoogleMeetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRescheduled")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RescheduledTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StudyTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TutorSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.HasIndex("TutorSubjectId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Models.Entities.BookingTransaction", b =>
                {
                    b.Property<Guid>("BookingTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BookingTransactionId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ReceiverWalletId");

                    b.HasIndex("SenderWalletId");

                    b.ToTable("BookingTransactions");
                });

            modelBuilder.Entity("Models.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("int");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId");

                    b.HasIndex("TutorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Models.Entities.CourseOutline", b =>
                {
                    b.Property<Guid>("CourseOutlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseOutlineId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseOutlines");
                });

            modelBuilder.Entity("Models.Entities.CoursePromotion", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("CoursePromotions");
                });

            modelBuilder.Entity("Models.Entities.CourseSchedule", b =>
                {
                    b.Property<Guid>("CourseSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseSlotId", "ScheduleId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("CourseSchedules");
                });

            modelBuilder.Entity("Models.Entities.CourseSlot", b =>
                {
                    b.Property<Guid>("CourseSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.HasKey("CourseSlotId");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseSlots");
                });

            modelBuilder.Entity("Models.Entities.CourseTransaction", b =>
                {
                    b.Property<Guid>("CourseTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ReceiverWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CourseTransactionId");

                    b.HasIndex("ReceiverWalletId");

                    b.HasIndex("SenderWalletId");

                    b.ToTable("CourseTransactions");
                });

            modelBuilder.Entity("Models.Entities.Moderator", b =>
                {
                    b.Property<Guid>("ModeratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ModeratorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Models.Entities.Promotion", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PromotionId");

                    b.HasIndex("TutorId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Models.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReportId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Models.Entities.ReportImages", b =>
                {
                    b.Property<Guid>("ReportImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReportImageId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportImages");
                });

            modelBuilder.Entity("Models.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScheduleId");

                    b.HasIndex("StudentCourseId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Models.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Models.Entities.StudentCourse", b =>
                {
                    b.Property<Guid>("StudentCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleMeetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("Models.Entities.StudentRequest", b =>
                {
                    b.Property<Guid>("StudentRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentRequestId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentRequests");
                });

            modelBuilder.Entity("Models.Entities.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Models.Entities.Tutor", b =>
                {
                    b.Property<Guid>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttractiveTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountMessageChat")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBoughtExperiencedPackage")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBoughtSubscription")
                        .HasColumnType("bit");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PricePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubcriptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubcriptionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubcriptionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TutorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("Models.Entities.TutorAction", b =>
                {
                    b.Property<Guid>("TutorActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModeratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorActionId");

                    b.HasIndex("ModeratorId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorActions");
                });

            modelBuilder.Entity("Models.Entities.TutorCertificate", b =>
                {
                    b.Property<Guid>("TutorCertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorCertificateId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorCertificates");
                });

            modelBuilder.Entity("Models.Entities.TutorDateAvailable", b =>
                {
                    b.Property<Guid>("TutorDateAvailableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("TutorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TutorWeekAvailableID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorDateAvailableID");

                    b.HasIndex("TutorID");

                    b.HasIndex("TutorWeekAvailableID");

                    b.ToTable("TutorDateAvailables");
                });

            modelBuilder.Entity("Models.Entities.TutorExperience", b =>
                {
                    b.Property<Guid>("TutorExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndYear")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TutorExperienceId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorExperiences");
                });

            modelBuilder.Entity("Models.Entities.TutorRating", b =>
                {
                    b.Property<Guid>("TutorRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RatePoints")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorRatingId");

                    b.HasIndex("BookingId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorRatings");
                });

            modelBuilder.Entity("Models.Entities.TutorRatingImage", b =>
                {
                    b.Property<Guid>("TutorRatingImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TutorRatingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorRatingImageId");

                    b.HasIndex("TutorRatingId");

                    b.ToTable("TutorRatingImages");
                });

            modelBuilder.Entity("Models.Entities.TutorSlotAvailable", b =>
                {
                    b.Property<Guid>("TutorSlotAvailableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TutorDateAvailableID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TutorID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorSlotAvailableID");

                    b.HasIndex("TutorDateAvailableID");

                    b.HasIndex("TutorID");

                    b.ToTable("TutorSlotAvailables");
                });

            modelBuilder.Entity("Models.Entities.TutorSubject", b =>
                {
                    b.Property<Guid>("TutorSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorSubjectId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorSubjects");
                });

            modelBuilder.Entity("Models.Entities.TutorWeekAvailable", b =>
                {
                    b.Property<Guid>("TutorWeekAvailableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TutorWeekAvailableId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorWeekAvailables");
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BanExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Banned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Fcm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBoughtSubscription")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestRefreshTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Entities.UserAuthentication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAuthentications");
                });

            modelBuilder.Entity("Models.Entities.UserBlock", b =>
                {
                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CreateUserId", "TargetUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UserBlocks");
                });

            modelBuilder.Entity("Models.Entities.UserFollow", b =>
                {
                    b.Property<Guid>("CreateUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CreateUserId", "TargetUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("Models.Entities.Wallet", b =>
                {
                    b.Property<Guid>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvalaibleAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastBalanceUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PendingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Models.Entities.WalletTransaction", b =>
                {
                    b.Property<Guid>("WalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReceiverWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("WalletTransactionId");

                    b.HasIndex("ReceiverWalletId");

                    b.HasIndex("SenderWalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("Models.Entities.Booking", b =>
                {
                    b.HasOne("Models.Entities.Student", "StudentNavigation")
                        .WithMany("BookingsNavigation")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("BookingsNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.TutorSubject", "TutorSubjectNavigation")
                        .WithMany("BookingNavigation")
                        .HasForeignKey("TutorSubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StudentNavigation");

                    b.Navigation("TutorNavigation");

                    b.Navigation("TutorSubjectNavigation");
                });

            modelBuilder.Entity("Models.Entities.BookingTransaction", b =>
                {
                    b.HasOne("Models.Entities.Booking", "BookingNavigation")
                        .WithOne("BookingTransactionNavigation")
                        .HasForeignKey("Models.Entities.BookingTransaction", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Wallet", "ReceiverWalletNavigation")
                        .WithMany("ReceiverBookingTransactionsNavigation")
                        .HasForeignKey("ReceiverWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Wallet", "SenderWalletNavigation")
                        .WithMany("SenderBookingTransactionsNavigation")
                        .HasForeignKey("SenderWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BookingNavigation");

                    b.Navigation("ReceiverWalletNavigation");

                    b.Navigation("SenderWalletNavigation");
                });

            modelBuilder.Entity("Models.Entities.Course", b =>
                {
                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("CoursesNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TutorNavigation");
                });

            modelBuilder.Entity("Models.Entities.CourseOutline", b =>
                {
                    b.HasOne("Models.Entities.Course", "CoursesNavigation")
                        .WithMany("CourseOutlinesNavigation")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CoursesNavigation");
                });

            modelBuilder.Entity("Models.Entities.CoursePromotion", b =>
                {
                    b.HasOne("Models.Entities.Course", "CourseNavigation")
                        .WithMany("CoursePromotionsNavigation")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Promotion", "PromotionNavigation")
                        .WithMany("CoursePromotionsNavigation")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseNavigation");

                    b.Navigation("PromotionNavigation");
                });

            modelBuilder.Entity("Models.Entities.CourseSchedule", b =>
                {
                    b.HasOne("Models.Entities.CourseSlot", "CourseSlotNavigation")
                        .WithMany("CourseSchedulesNavigation")
                        .HasForeignKey("CourseSlotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Schedule", "ScheduleNavigation")
                        .WithMany("CourseSchedulesNavigation")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseSlotNavigation");

                    b.Navigation("ScheduleNavigation");
                });

            modelBuilder.Entity("Models.Entities.CourseSlot", b =>
                {
                    b.HasOne("Models.Entities.Course", "CourseNavigation")
                        .WithMany("CourseSlotsNavigation")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseNavigation");
                });

            modelBuilder.Entity("Models.Entities.CourseTransaction", b =>
                {
                    b.HasOne("Models.Entities.Course", "CourseNavigation")
                        .WithOne("CourseTransactionNavigation")
                        .HasForeignKey("Models.Entities.CourseTransaction", "CourseTransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Wallet", "ReceiverWalletNavigation")
                        .WithMany("ReceiverCourseTransactionsNavigation")
                        .HasForeignKey("ReceiverWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Wallet", "SenderWalletNavigation")
                        .WithMany("SenderCourseTransactionsNavigation")
                        .HasForeignKey("SenderWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseNavigation");

                    b.Navigation("ReceiverWalletNavigation");

                    b.Navigation("SenderWalletNavigation");
                });

            modelBuilder.Entity("Models.Entities.Moderator", b =>
                {
                    b.HasOne("Models.Entities.User", "UserNavigation")
                        .WithOne("ModeratorNavigation")
                        .HasForeignKey("Models.Entities.Moderator", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Models.Entities.Notification", b =>
                {
                    b.HasOne("Models.Entities.User", "UserNavigation")
                        .WithMany("NotificationNavigation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Models.Entities.Promotion", b =>
                {
                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("PromotionsNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TutorNavigation");
                });

            modelBuilder.Entity("Models.Entities.Report", b =>
                {
                    b.HasOne("Models.Entities.User", "UserNavigation")
                        .WithMany("SenderUserReportNavigation")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Models.Entities.ReportImages", b =>
                {
                    b.HasOne("Models.Entities.Report", "ReportNavigation")
                        .WithMany("ReportImages")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReportNavigation");
                });

            modelBuilder.Entity("Models.Entities.Schedule", b =>
                {
                    b.HasOne("Models.Entities.StudentCourse", "StudentCourseNavigation")
                        .WithMany("SchedulesNavigations")
                        .HasForeignKey("StudentCourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StudentCourseNavigation");
                });

            modelBuilder.Entity("Models.Entities.Student", b =>
                {
                    b.HasOne("Models.Entities.User", "UserNavigation")
                        .WithOne("StudentNavigation")
                        .HasForeignKey("Models.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Models.Entities.StudentCourse", b =>
                {
                    b.HasOne("Models.Entities.Course", "CourseNavigation")
                        .WithMany("StudentCoursesNavigation")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Student", "StudentNavigation")
                        .WithMany("StudentCoursesNavigation")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CourseNavigation");

                    b.Navigation("StudentNavigation");
                });

            modelBuilder.Entity("Models.Entities.StudentRequest", b =>
                {
                    b.HasOne("Models.Entities.Student", "StudentNavigation")
                        .WithMany("StudentRequestsNavigation")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Subject", "SubjectNavigation")
                        .WithMany("StudentRequestsNavigation")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StudentNavigation");

                    b.Navigation("SubjectNavigation");
                });

            modelBuilder.Entity("Models.Entities.Tutor", b =>
                {
                    b.HasOne("Models.Entities.User", "UserNavigation")
                        .WithOne("TutorNavigation")
                        .HasForeignKey("Models.Entities.Tutor", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorAction", b =>
                {
                    b.HasOne("Models.Entities.Moderator", "ModeratorNavigation")
                        .WithMany("TutorActionsNavigation")
                        .HasForeignKey("ModeratorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("TutorActionsNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ModeratorNavigation");

                    b.Navigation("TutorNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorCertificate", b =>
                {
                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("TutorCertificatesNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TutorNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorDateAvailable", b =>
                {
                    b.HasOne("Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorDateAvailablesNavigation")
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.TutorWeekAvailable", "TutorWeekAvailable")
                        .WithMany("TutorDateAvailables")
                        .HasForeignKey("TutorWeekAvailableID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tutor");

                    b.Navigation("TutorWeekAvailable");
                });

            modelBuilder.Entity("Models.Entities.TutorExperience", b =>
                {
                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("TutorExperiencesNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TutorNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorRating", b =>
                {
                    b.HasOne("Models.Entities.Booking", "BookingNavigation")
                        .WithMany("TutorRatingsNavigation")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Student", "StudentNavigation")
                        .WithMany("TutorRatingsNavigation")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("TutorRatingsNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BookingNavigation");

                    b.Navigation("StudentNavigation");

                    b.Navigation("TutorNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorRatingImage", b =>
                {
                    b.HasOne("Models.Entities.TutorRating", "TutorRatingNavigation")
                        .WithMany("TutorRatingImagesNavigation")
                        .HasForeignKey("TutorRatingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TutorRatingNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorSlotAvailable", b =>
                {
                    b.HasOne("Models.Entities.TutorDateAvailable", "TutorDateAvailable")
                        .WithMany("TutorSlotAvailables")
                        .HasForeignKey("TutorDateAvailableID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorSlotAvailablesNavigation")
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tutor");

                    b.Navigation("TutorDateAvailable");
                });

            modelBuilder.Entity("Models.Entities.TutorSubject", b =>
                {
                    b.HasOne("Models.Entities.Subject", "SubjectNavigation")
                        .WithMany("TutorSubjectNavigation")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Tutor", "TutorNavigation")
                        .WithMany("TutorSubjectsNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SubjectNavigation");

                    b.Navigation("TutorNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorWeekAvailable", b =>
                {
                    b.HasOne("Models.Entities.Tutor", "Tutor")
                        .WithMany("TutorWeekAvailablesNavigation")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Models.Entities.UserAuthentication", b =>
                {
                    b.HasOne("Models.Entities.User", "UserNavigation")
                        .WithMany("UserAuthenticationNavigation")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Models.Entities.UserBlock", b =>
                {
                    b.HasOne("Models.Entities.User", "CreateUserNavigation")
                        .WithMany("CreateUserBlockNavigation")
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.User", "TargetUserNavigation")
                        .WithMany("TargetUserBlockNavigation")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreateUserNavigation");

                    b.Navigation("TargetUserNavigation");
                });

            modelBuilder.Entity("Models.Entities.UserFollow", b =>
                {
                    b.HasOne("Models.Entities.User", "CreateUserNavigation")
                        .WithMany("CreateUserFollowNavigation")
                        .HasForeignKey("CreateUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.User", "TargetUserNavigation")
                        .WithMany("TargetUserFollowNavigation")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreateUserNavigation");

                    b.Navigation("TargetUserNavigation");
                });

            modelBuilder.Entity("Models.Entities.Wallet", b =>
                {
                    b.HasOne("Models.Entities.User", "UserNavigation")
                        .WithOne("WalletNavigation")
                        .HasForeignKey("Models.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("Models.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Models.Entities.Wallet", "ReceiverWalletNavigation")
                        .WithMany("ReceiverWalletTransactionsNavigation")
                        .HasForeignKey("ReceiverWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Wallet", "SenderWalletNavigation")
                        .WithMany("SenderWalletTransactionsNavigation")
                        .HasForeignKey("SenderWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReceiverWalletNavigation");

                    b.Navigation("SenderWalletNavigation");
                });

            modelBuilder.Entity("Models.Entities.Booking", b =>
                {
                    b.Navigation("BookingTransactionNavigation");

                    b.Navigation("TutorRatingsNavigation");
                });

            modelBuilder.Entity("Models.Entities.Course", b =>
                {
                    b.Navigation("CourseOutlinesNavigation");

                    b.Navigation("CoursePromotionsNavigation");

                    b.Navigation("CourseSlotsNavigation");

                    b.Navigation("CourseTransactionNavigation");

                    b.Navigation("StudentCoursesNavigation");
                });

            modelBuilder.Entity("Models.Entities.CourseSlot", b =>
                {
                    b.Navigation("CourseSchedulesNavigation");
                });

            modelBuilder.Entity("Models.Entities.Moderator", b =>
                {
                    b.Navigation("TutorActionsNavigation");
                });

            modelBuilder.Entity("Models.Entities.Promotion", b =>
                {
                    b.Navigation("CoursePromotionsNavigation");
                });

            modelBuilder.Entity("Models.Entities.Report", b =>
                {
                    b.Navigation("ReportImages");
                });

            modelBuilder.Entity("Models.Entities.Schedule", b =>
                {
                    b.Navigation("CourseSchedulesNavigation");
                });

            modelBuilder.Entity("Models.Entities.Student", b =>
                {
                    b.Navigation("BookingsNavigation");

                    b.Navigation("StudentCoursesNavigation");

                    b.Navigation("StudentRequestsNavigation");

                    b.Navigation("TutorRatingsNavigation");
                });

            modelBuilder.Entity("Models.Entities.StudentCourse", b =>
                {
                    b.Navigation("SchedulesNavigations");
                });

            modelBuilder.Entity("Models.Entities.Subject", b =>
                {
                    b.Navigation("StudentRequestsNavigation");

                    b.Navigation("TutorSubjectNavigation");
                });

            modelBuilder.Entity("Models.Entities.Tutor", b =>
                {
                    b.Navigation("BookingsNavigation");

                    b.Navigation("CoursesNavigation");

                    b.Navigation("PromotionsNavigation");

                    b.Navigation("TutorActionsNavigation");

                    b.Navigation("TutorCertificatesNavigation");

                    b.Navigation("TutorDateAvailablesNavigation");

                    b.Navigation("TutorExperiencesNavigation");

                    b.Navigation("TutorRatingsNavigation");

                    b.Navigation("TutorSlotAvailablesNavigation");

                    b.Navigation("TutorSubjectsNavigation");

                    b.Navigation("TutorWeekAvailablesNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorDateAvailable", b =>
                {
                    b.Navigation("TutorSlotAvailables");
                });

            modelBuilder.Entity("Models.Entities.TutorRating", b =>
                {
                    b.Navigation("TutorRatingImagesNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorSubject", b =>
                {
                    b.Navigation("BookingNavigation");
                });

            modelBuilder.Entity("Models.Entities.TutorWeekAvailable", b =>
                {
                    b.Navigation("TutorDateAvailables");
                });

            modelBuilder.Entity("Models.Entities.User", b =>
                {
                    b.Navigation("CreateUserBlockNavigation");

                    b.Navigation("CreateUserFollowNavigation");

                    b.Navigation("ModeratorNavigation");

                    b.Navigation("NotificationNavigation");

                    b.Navigation("SenderUserReportNavigation");

                    b.Navigation("StudentNavigation");

                    b.Navigation("TargetUserBlockNavigation");

                    b.Navigation("TargetUserFollowNavigation");

                    b.Navigation("TutorNavigation");

                    b.Navigation("UserAuthenticationNavigation");

                    b.Navigation("WalletNavigation");
                });

            modelBuilder.Entity("Models.Entities.Wallet", b =>
                {
                    b.Navigation("ReceiverBookingTransactionsNavigation");

                    b.Navigation("ReceiverCourseTransactionsNavigation");

                    b.Navigation("ReceiverWalletTransactionsNavigation");

                    b.Navigation("SenderBookingTransactionsNavigation");

                    b.Navigation("SenderCourseTransactionsNavigation");

                    b.Navigation("SenderWalletTransactionsNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
